/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/6.8.3/samples
 */

 plugins {
     java
 }

 repositories {
    maven(url = "https://papermc.io/repo/repository/maven-public/")
 }

 dependencies {
    compileOnly("com.destroystokyo.paper:paper-api:1.16.5-R0.1-SNAPSHOT")
 }

 java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(16))
    }
}

tasks.withType<JavaCompile>().configureEach { 
    options.setIncremental(false)
    options.headerOutputDirectory.set(file("src/main/headers"))
}